% This script renders some images at fixed levels of the hue.

%%
tic;
outputName = 'Test2';
RunToyVirtualWorldRecipes('outputName',outputName, ...
    'imageWidth',320, ...
    'imageHeight',240, ...
    'fovinDegrees', 17, ...
    'cropImageHalfSize', 100, ...
    'nOtherObjectSurfaceReflectance', 999, ... % Number of random surfaces to choose from
    'hueLevels',linspace(0.1, 1.0,2), ...
    'reflectanceNumbers',(1:3), ...
    'nInsertedLights', 1, ...
    'nInsertObjects', 0, ... % These are objects other than target objects
    'otherObjectReflectanceRandom', true, ...
    'baseSceneReflectancesSameAcrossInterval', true,...
    'otherObjectReflectancesSameAcrossInterval', true,...
    'covScaleFactor', 1,...
    'illuminantSpectraRandom', false, ...
    'illuminantSpectraSameShape', false,...
    'minMeanIlluminantLevel', 0.75, ...
    'maxMeanIlluminantLevel', 1.25, ...
    'illuminantScaling', 1, ...    
    'illuminantSpectrumNotFlat',true, ...
    'illCovScaleFactor', 0,...
    'bMakeD65',true, ...
    'targetSpectrumNotFlat', false, ...    
    'allTargetSpectrumSameShape', true, ...
    'targetReflectanceScaledCopies', true, ...
    'lightPositionRandom',false, ...
    'lightScaleRandom',false, ...
    'targetPositionRandom',false, ...
    'targetScaleRandom',false, ...
    'targetRotationRandom',false, ...
    'objectShapeSet',{'BigBall'}, ...
    'lightShapeSet',{'BigBall'}, ...
    'baseSceneSet',{'Library'}, ...    
    'mosaicHalfSize', 25, ...
    'integrationTime', 100/1000, ... % in sec
    'nRandomRotations', 0, ...
    'maxDepth', 2);
toc

%%
tic;
MakeMultispectralStruct(...
    'folderName',outputName,...
    'hueLevels', linspace(0.1, 1.0,2), ...
    'reflectanceNumbers', (1:3), ...
    'targetShape', 'BigBall', ...
    'baseScene', 'Library', ...
    'cropImageHalfSizeX', 100, ...
    'cropImageHalfSizeY', 100);
toc

%%
makeCroppedImageMontageAllLevels(outputName,201,linspace(0.1, 1.0,2), [1:3],0.005);

%%
startup;
tbUseProject('VirtualWorldPsychophysics');
multispectralStructToLMSStruct(...
    'multipsectralStructFolder',outputName,...
    'LMSStructFolder',outputName,...
    'outputFileName','LMSStruct');